#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    user = sys.argv[1]
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    tweets = get_user_timeline(user, 50)
    if tweets == None:
        sys.exit("Usage: incorect @screen_name")

    for tweet in tweets:
        # instantiate analyzer
        analyzer = Analyzer(positives, negatives)
        score = analyzer.analyze(tweet)

        if score > 0.0:
            print(colored(":) {}".format(tweet), "green"))
        elif score < 0.0:
            print(colored(":( {}".format(tweet), "red"))
        else:
            print(colored(":| {}".format(tweet), "yellow"))

if __name__ == "__main__":
    main()

